### ISSUE TITLE
Chose and configure an unit test framework for tests

### ISSUE THREAD

**Issue by akafael** [akafael/ufpe-project-bsg#5]
# Tasks

In order to better organize our work schedule, it is necessary to answer the questions described in the to-do list bellow, refering to the tasks related to software testing.

- [x] Define which frameworks will be used to test the code: **Unity, Criterion, Google Test**,...
- [x] If necessary, define a library to evaluate **test coverage**
- [x] Define which group members will be responsible for testing the software
- [ ] Define whether or not strategies such as **test mutation** will be used
- [ ] Define what percentage of test coverage is acceptable
- [x] Define which file format will be used to generate test reports
- [x] Define if test generator tools will be used
- [x] If not, define how many test cases we intend to write

**Comment by SSDaniel** [comment]
For now, these ideas below are too much. We will work on them later. 
->Define whether or not strategies such as test mutation will be used
->Define what percentage of test coverage is acceptable
